### ISSUE TITLE
allow changing gremlin zindex

### ISSUE THREAD

**Issue by leonpegg** [marmelab/gremlins.js#100]
when using gremlins with framework7.io the actions dont show as they are to low in the z-index would be good to be able to customise the i-index as at the moment i have to manually change it in four locations

**Comment by zyhou** [comment]
Hey folks. The Marmelab team is attempting to clean up the Issues backlog. With that, we're closing issues that have been open for an one or more years.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. If the issue pertains to a bug, please re-test for the bug on the latest version of gremlins.js.

The best way to report problems with gremlins.js 2.0 is to file new issues.
