### ISSUE TITLE
I noticed that when a gremlin interacts with a canvas no events are triggered

### ISSUE THREAD

**Issue by Lazerbeak12345** [marmelab/gremlins.js#102]
I am using _jQuery_ for these events to set the handler, and I think this may be the problem. Perhaps this api should also trigger jQuery events, if possible. (Please note that the user **can** "draw" on this canvas by simply clicking and dragging the cursor )

**Comment by zyhou** [comment]
Hey folks. The Marmelab team is attempting to clean up the Issues backlog. With that, we're closing issues that have been open for an one or more years.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. If the issue pertains to a bug, please re-test for the bug on the latest version of gremlins.js.

The best way to report problems with gremlins.js 2.0 is to file new issues.
