### ISSUE TITLE
Is there a way to run gremlin Monkey Tests on third party URLs? 

### ISSUE THREAD

**Issue by nik-john** [marmelab/gremlins.js#103]
Is it possible to run Gremlin tests on third party URLs or external websites? For e.g. If I want to run gremlin on Twitter.com, what would I have to do? I've not tried it yet, but I'm thinking a framework like nightwatch.js might be handy, but I'm not sure about how to go about it.

**Comment by tomlutzenberger** [comment]
You can use the bookmarklet and execute it on every website.
Take a look at
https://github.com/marmelab/gremlins.js#installation
and 
https://rawgit.com/marmelab/gremlins.js/master/bookmarklet.html

**Comment by nik-john** [comment]
Ah I see. That worked. On a couple of sites. There's no getting around the CSP though? I'm trying to run gremlin on Facebook and Inbox, but CSP prevents gremlin from running on these sites. Works like a charm on Medium though

**Comment by tomlutzenberger** [comment]
Not sure if you can bypass CSP. Maybe there's a browser setting.

**Comment by zyhou** [comment]
Hey folks. The Marmelab team is attempting to clean up the Issues backlog. With that, we're closing issues that have been open for an one or more years.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. If the issue pertains to a bug, please re-test for the bug on the latest version of gremlins.js.

The best way to report problems with gremlins.js 2.0 is to file new issues.
