### ISSUE TITLE
Prevent External Links Opens

### ISSUE THREAD

**Issue by stripathi669** [marmelab/gremlins.js#104]
Say my site points to Google play.

I want gremlins to remain in my site only. That is, prevent opening any external link

**Comment by JackC27** [comment]
"Not prevent opening any external link" is 'Not' a typo?

**Comment by stripathi669** [comment]
@JackC27 Yeah. Sorry about that.

**Comment by kafeltz** [comment]
You could edit your question after knowing the typo.

**Comment by zyhou** [comment]
Hey folks. The Marmelab team is attempting to clean up the Issues backlog. With that, we're closing issues that have been open for an one or more years.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. If the issue pertains to a bug, please re-test for the bug on the latest version of gremlins.js.

The best way to report problems with gremlins.js 2.0 is to file new issues.
