### ISSUE TITLE
Is there any way to logs all gremlin actions and mogwai observations in  Local file

### ISSUE THREAD

**Issue by tonyying** [marmelab/gremlins.js#109]
**Hi,**

**I want to testing web page just use one command, and logs all gremlin actions and mogwai observations in  Local file,is it posible?**

**Is it right to use like this:**
javascript:(function(){function callback(){var horde = gremlins.createHorde();var customLogger = {log:   function(msg) { /* do sth. */ },info:  function(msg) { /* do sth. */ },warn:  function(msg) { /* do sth. */ },error: function(msg) { /* do sth. */ }};horde.logger(customLogger);horde.unleash();} var s=document.createElement("script");s.src="http://127.0.0.1:8099/gremlins.js-master/gremlins.min.js";if(s.addEventListener){s.addEventListener("load",callback,false)}else if(s.readyState){s.onreadystatechange=callback}document.body.appendChild(s);})()

**thanks for any help :)**

**Comment by zyhou** [comment]
Hey folks. The Marmelab team is attempting to clean up the Issues backlog. With that, we're closing issues that have been open for an one or more years.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. If the issue pertains to a bug, please re-test for the bug on the latest version of gremlins.js.

The best way to report problems with gremlins.js 2.0 is to file new issues.
