### ISSUE TITLE
Problems Ember.js

### ISSUE THREAD

**Issue by jonasbuechel** [marmelab/gremlins.js#110]
I tried to use gremlins.js in a ember.js app. Default HTML form elements are used, but any component which has a custom action like 'click' doesn't fire at a gremlins.js click.

Maybe it's the same problem like: https://github.com/marmelab/gremlins.js/issues/88

**Comment by zyhou** [comment]
Hey folks. The Marmelab team is attempting to clean up the Issues backlog. With that, we're closing issues that have been open for an one or more years.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. If the issue pertains to a bug, please re-test for the bug on the latest version of gremlins.js.

The best way to report problems with gremlins.js 2.0 is to file new issues.
