### ISSUE TITLE
Use gremlins with Test runner in Angular 

### ISSUE THREAD

**Issue by bjverhoe** [marmelab/gremlins.js#112]
Hi, 

Recently I discovered this project, and it looks like a great tool!

Currently the way to test a page is by including the minified script in the `index.html` file and unleash the horde. However, I've not yet managed to make this work for Angular (v4). 

I was wondering what the best strategy would be to implement this?

Next to this, is there any support for a test runner to run a test with gremlins? Like using Karma/Protractor to run this test.

**Comment by rlwhatley3** [comment]
Minor implementation available at https://www.npmjs.com/package/protractor-gremlins-plugin
Currently the plugin only supports very basic usage of a default horde. More to come with future versions.

**Comment by zyhou** [comment]
Hey folks. The Marmelab team is attempting to clean up the Issues backlog. With that, we're closing issues that have been open for an one or more years.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. If the issue pertains to a bug, please re-test for the bug on the latest version of gremlins.js.

The best way to report problems with gremlins.js 2.0 is to file new issues.
