### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [marmelab/gremlins.js#129]
Hi, what is the current status of the project? Are you looking for new maintainers?

**Comment by fzaninotto** [comment]
Hi Daniel, thanks for asking.

Indeed, we have chosen to spend our open-source time on other projects for now (specifically on [react-admin](https://github.com/marmelab/react-admin), which we use a lot internally). 

If you're willing to give us a hand on gremlins.js, we'd love it!

**Comment by schmunk42** [comment]
So, any news on this?

**Comment by fzaninotto** [comment]
We're still on other priorities, but we'll definitely give the Gremlins project some love later this year.

**Comment by zyhou** [comment]
It’s time to give some love to this useful and fun package ! @Pierre and I are the new maintainers of this project.

We already publish a [gremlins.js 2.0](https://www.npmjs.com/package/gremlins.js) and refresh the [readme](https://github.com/marmelab/gremlins.js#gremlinsjs) file.
