### ISSUE TITLE
Example of bugs?

### ISSUE THREAD

**Issue by goldbergyoni** [marmelab/gremlins.js#131]
Such a great project, thanks. I want to to show it live at some conf, do you have an example of some UI (maybe even known site) that was proven buggy using this tool?

**Comment by Kmaschta** [comment]
@fzaninotto might help you answer this question (but do not expect an answer this week)

In the meantime, I would suggest you to go through the dependents list: https://github.com/marmelab/gremlins.js/network/dependents

**Comment by i0natan** [comment]
@fzaninotto Maybe some example pops to your mind?

**Comment by zyhou** [comment]
Hey folks. The Marmelab team is attempting to clean up the Issues backlog. With that, we're closing issues that have been open for an one or more years.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. If the issue pertains to a bug, please re-test for the bug on the latest version of gremlins.js.

The best way to report problems with gremlins.js 2.0 is to file new issues.
