### ISSUE TITLE
Bug: Uncaught RangeError: Chance: Min cannot be greater than Max.

### ISSUE THREAD

**Issue by ps-george** [marmelab/gremlins.js#159]
Getting Uncaught RangeError with Chance using gremlins.js in Cypress. Solution seems simple to implement.

-   `gremlins.js` version:  2.0.1
-   `node` version: 12.9.0
-   `npm` (or `yarn`) version: 6.10.2
-   browser version: electron 80 or Firefox 

## Steps To Reproduce

1. Run gremlins.js with Cypress.

## The current behavior

```
RangeError
Chance: Min cannot be greater than Max.
View stack trace
RangeError: Chance: Min cannot be greater than Max.
testRange@http://localhost:3000/__cypress/tests?p=cypress/integration/netherplane.js-019:2218:20
[5]</</</chance_1</</Chance.prototype.integer@http://localhost:3000/__cypress/tests?p=cypress/integration/netherplane.js-019:2401:19
[5]</</</chance_1</</Chance.prototype.natural@http://localhost:3000/__cypress/tests?p=cypress/integration/netherplane.js-019:2443:22
defaultPositionSelector@http://localhost:3000/__cypress/tests?p=cypress/integration/netherplane.js-019:9892:25
clicker/</<@http://localhost:3000/__cypress/tests?p=cypress/integration/netherplane.js-019:9955:32
executeInSeries/</<@http://localhost:3000/__cypress/tests?p=cypress/integration/netherplane.js-019:10735:61
```

## The expected behavior
No error.

### Suggested solution:

Probably quite similar to #27  and #47 .
Culprit is here:

```
const defaultPositionSelector = () => {
	        return [
	            randomizer.natural({
	                max: document.documentElement.clientWidth - 1,
	            }),
	            randomizer.natural({
	                max: document.documentElement.clientHeight - 1,
	            }),
	        ];
	    };
```
Solution: Use `||` or `Math.max(document.documentElement.clientWidth - 1, 0)`

**Comment by ps-george** [comment]
Changes I made to fix this issue:

**Comment by zyhou** [comment]
Thanks for the report.

I agree with you fix, can you open a pull request ?

**Comment by HALLERPierre** [comment]
Done in https://github.com/marmelab/gremlins.js/pull/160. 
Thanks

**Comment by zyhou** [comment]
Deploy on npm, [https://github.com/marmelab/gremlins.js/blob/master/CHANGELOG.md#210-2020-04-22](changelog)
