### ISSUE TITLE
Bug: Input with `type="number"` breaks gremlins

### ISSUE THREAD

**Issue by TLHM** [marmelab/gremlins.js#162]
Running a basic horde of gremlins on a page with an input tag with the type of "number" causes an error (pasted below).

-   `gremlins.js` version: ^2.1.0
-   `node` version: v12.16.2
-   `npm` (or `yarn`) version: npm 6.14.4
-   browser version: Firefox 74.0.1 or Chrome Version 81.0.4044.122

## Steps To Reproduce

1. Load page with a tag like:
`<input type="number">`
2. Unleash gremlins via bookmarklet

Link to code example:

```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Break the gremlins</title>
  </head>
  <body>
    <input type="number">
  </body>
</html>
```

## The current behavior

```
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyDescriptor (<anonymous>)
    at n (gremlins.min.js:1)
    at Object.input[type="number"] (gremlins.min.js:1)
    at gremlins.min.js:1
    at gremlins.min.js:1
    at async r (gremlins.min.js:1)
    at async Promise.all (:8080/index 0)
    at async Object.unleash (gremlins.min.js:1)
  | n | @ | gremlins.min.js:1
-- | -- | -- | --
  | input[type="number"] | @ | gremlins.min.js:1
  | (anonymous) | @ | gremlins.min.js:1
  | (anonymous) | @ | gremlins.min.js:1
  | async function (async) |   |  
  | unleash | @ | gremlins.min.js:1
  | (anonymous) | @ | index.js:253
  | (anonymous) | @ | on.js:27
```

## The expected behavior

Normal horde behavior

**Comment by HALLERPierre** [comment]
Thank you for you report. 
It'll be fix in the next release.

**Comment by zyhou** [comment]
Nice catch :)

**Comment by CodeTako** [comment]
Awesome, thanks for the quick work!
