### ISSUE TITLE
Incorrect params for `customGremlin` in README

### ISSUE THREAD

**Issue by CodeWithOz** [marmelab/gremlins.js#170]
The [`Basic Usage`](https://github.com/marmelab/gremlins.js#basic-usage) section of the README shows that the `customGremlin` function accepts 2 arguments, `logger` and `randomizer`, but in v2.2.0 the function receives only one argument which is an object that contains `logger`, `randomizer`, and `window` properties. Perhaps the `Basic Usage` code was meant to be this:
```
function customGremlin({logger, randomizer}) {
...
```

**Comment by HALLERPierre** [comment]
Hi and thank you for your issue :smile: !

Yes you're absolutely right, the readme is wrong.
The correct way is:
```js
function customGremlin({ logger, randomizer, window }) {
...
```

**Comment by HALLERPierre** [comment]
I updated the Readme.
