### ISSUE TITLE
Command line interface?

### ISSUE THREAD

**Issue by FelixBenning** [marmelab/gremlins.js#171]
🚨 The issue tracker is not for implementation questions 🚨

(This might be a feature request if it is not currently possible to do what I want to do)

I am looking for a tool to do a basic smoke test on [Plotly Dash](https://plotly.com/dash/)/[RShiny](https://shiny.rstudio.com/) Dashboards. These apps are going to be containerized and the tests would be part of a [gitlab-ci](https://docs.gitlab.com/ee/ci/) job. GitLab ci jobs are essenstially a small command line script which are executed by runners (which usually generate a container for that - assuming the runner type docker). So I would essentially use docker-compose in the first part of the script (docker in docker) and then I would like to be able to use a monkey test on the generated webpage exposed on a port of the container.

Now this Project (https://github.com/morkeleb/clickmonkey) seems to be pretty much what I want: Specify a url in a config file and simply start the mayhem with the command line command `clickmonkey`.

But it is a very niche project compared to `gremlins.js` (6 stars vs 8.5k stars), which is why I am a bit hesitant to use it. On the other hand I am not sure if I understand the installation instructions of `gremlin.js` since there is no mention of "pointing them at a url". So I am now *thinking* that you have to include them as a dependency into an existing (node.js?) project. It says it is also available as a bookmarklet. I am not sure if that is what I am looking for - docker containers probably do not have browsers installed. 

So do I understand it correctly that you do not currently support a command line interface? And if so, is it possible to include gremlins into a non-node.js project like the above dashboard generation frameworks?

**Comment by HALLERPierre** [comment]
Hello Felix and thanks for opening an issue.

The library you're talking about seems to install Selenium. Gremlins.js is a standalone library.
So it doesn't come with a browser or anything like that.

To run gremlins.js on a given url in a CI environment you'll need to use something like [Cypress](https://www.cypress.io/) (or selenium, like clickmonkey).

You can find documentations about running cypress in a docker container pretty easily.

Once you have a running container with cypress you can write your tests pretty easily, we have a working example here: 
https://github.com/marmelab/gremlins.js/blob/master/cypress/integration/formFiller.spec.js

Good luck !

**Comment by FelixBenning** [comment]
Thank you for the pointers!
