### ISSUE TITLE
Using Within Playwright

### ISSUE THREAD

**Issue by ilrein** [marmelab/gremlins.js#175]
I see the docs has an example of how to use gremlins within cypress. Is there a way to do the same, but using [Playwright](https://playwright.dev/) instead?

**Comment by airwreck1122** [comment]
test

**Comment by airwreck1122** [comment]
test

**Comment by npantelaios** [comment]
I have the same question, does this work with playwright? My code is like this:

 **await page.evaluate(() => { gremlins.createHorde().unleash()}).catch(e => void 0);**

And I get _window is not defined_ error. Any help?

**Comment by jfgreffier** [comment]
Here is something that worked for me

```
import { test } from "@playwright/test";

test("run gremlins.js", async ({ page }) => {
  await page.addInitScript({
    path: "./node_modules/gremlins.js/dist/gremlins.min.js",
  });
  await page.goto("https://playwright.dev");
  await page.evaluate(() => gremlins.createHorde().unleash());
});
```

**Comment by jfgreffier** [comment]
Hi there! I've made a pull request to add an example for Playwright
