### ISSUE TITLE
Interactions not completely deterministic despite seeding the randomizer

### ISSUE THREAD

**Issue by Piedone** [marmelab/gremlins.js#185]
We seed the randomizer as instructed [in the docs](https://github.com/marmelab/gremlins.js#seeding-the-randomizer) as you can see in our code [here](https://github.com/Lombiq/UI-Testing-Toolbox/blob/task/monkey-testing/Lombiq.Tests.UI/MonkeyTesting/GremlinsScripts.cs#L62). Despite this, we observed that the interactions are not completely deterministic, see [here](https://github.com/Lombiq/UI-Testing-Toolbox/pull/109#discussion_r793366272).

What is it that we can be missing? Thank you!

**Comment by fzaninotto** [comment]
No idea. Did you add custom species / strategies ? Did you use Math.Random in them?

**Comment by Piedone** [comment]
Yes, we do add a custom strategy [here](https://github.com/Lombiq/UI-Testing-Toolbox/blob/task/monkey-testing/Lombiq.Tests.UI/MonkeyTesting/GremlinsScripts.cs#L56) and use [this list of species](https://github.com/Lombiq/UI-Testing-Toolbox/blob/task/monkey-testing/Lombiq.Tests.UI/MonkeyTesting/MonkeyTestingOptions.cs#L46). However, all of this just configuring built-in gremlins.js functionality and we don't use any custom randomization logic there.

Do we understand correctly that the randomizer setup [here](https://github.com/Lombiq/UI-Testing-Toolbox/blob/task/monkey-testing/Lombiq.Tests.UI/MonkeyTesting/GremlinsScripts.cs#L62) should be enough for deterministic execution (if the given seen is constant, which it is)?

**Comment by fzaninotto** [comment]
I'm sorry, as you're rendering JS through a templating system, I can't see the code that you're running. Could you build a self-sufficient repro in Codesandbox?

**Comment by Piedone** [comment]
As it turned out, this wasn't an issue with gremlins.js. Rather, an animation on the site and its varying timing (due to the capabilities of the machine it was executed on) caused flakiness.

Thanks for your help!
