### ISSUE TITLE
Add an http throttle gremlin

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/gremlins.js#23]
create a facade to the XmlHttpRequest object to add random response latency

**Comment by HALLERPierre** [comment]
Hey folks. The Marmelab team is attempting to clean up the Issues backlog. With that, we're closing issues that have been open for an one or more years.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. If the issue pertains to a bug, please re-test for the bug on the latest version of gremlins.js.

The best way to report problems with gremlins.js 2.0 is to file new issues.
