### ISSUE TITLE
gremlins don't trigger click handlers?

### ISSUE THREAD

**Issue by sylvain-hamel** [marmelab/gremlins.js#55]
I can see the gremlins clicking everywhere on my page but click handlers are not called. I have `buttons` and `a` that show messages or expend areas of the page and they don't kick-in.

My app is an AngularJS app. I tried giving some time for the app to bootstrap before I `unleash` but it does not change the result.

```
    <script src="tests/lib/gremlins.min.js"></script>
    <script>
        $(function () {
            setTimeout(function () {
                gremlins.createHorde().unleash();
            }, 3000)
        })
    </script>
```

**Comment by elmccd** [comment]
For me this piece of code does not trigger click events:
```javascript
gremlins.createHorde().unleash();
```
This one do:
```javascript
gremlins.createHorde()
.gremlin(gremlins.species.clicker().clickTypes(['click']))
.unleash();
```

I don't know if this is correct behavior, but I think this is what are guys about.

**Comment by HALLERPierre** [comment]
Hey folks. The Marmelab team is attempting to clean up the Issues backlog. With that, we're closing issues that have been open for an one or more years.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. If the issue pertains to a bug, please re-test for the bug on the latest version of gremlins.js.

The best way to report problems with gremlins.js 2.0 is to file new issues.
