### ISSUE TITLE
Allow the lib to work in node.js

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/gremlins.js#6]
see how async.js supports both the browser and Node

**Comment by anied** [comment]
Hi-- I got started with Gremlins today at work to leverage for a NodeJS application.  I had some ideas-- are you guys interested in contributors to help fleshing out NodeJS support?

**Comment by HALLERPierre** [comment]
Hey folks. The Marmelab team is attempting to clean up the Issues backlog. With that, we're closing issues that have been open for an one or more years.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. If the issue pertains to a bug, please re-test for the bug on the latest version of gremlins.js.

The best way to report problems with gremlins.js 2.0 is to file new issues.
