### ISSUE TITLE
Test with zombie.js

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/gremlins.js#7]
MAke sure all tests can run in a headless browser

**Comment by jhulme** [comment]
Is this still an open issue?

I have run each of the available examples (basic, TodoMVC and touch) with casperjs and no observable failures.

There is an issue with the logging output from the formFiller.js and toucher.js when passing an object to the .logger(). 

Casperjs returns [ object Object ] or [ HTML Object ] due to the fact that Phantomjs only supports basic strings for console logging.

Example:

    gremlin toucher    multitouch at 393 37 [object Object]

**Comment by mickaelandrieu** [comment]
@jhulme you are right, but I'm not sure we have to use casperjs as this is a "maintained but not too much" project.

Also, there is a lot of better testing frameworks like zombie.js (2?) so that's why I finaly "don't" suggest any PR using casperjs.

**Comment by jhulme** [comment]
Thanks @mickaelandrieu I will take a look at zombie.js

**Comment by dbartholomae** [comment]
The following worked for me when running with puppetteer:
```typescript
import fs from 'fs'
import { Page } from 'puppeteer'

export async function runGremlins (page: Page) {
  const gremlinsFile = require.resolve('gremlins.js/gremlins.min.js')
  const gremlins = fs.readFileSync(gremlinsFile, 'utf8')
  await page.addScriptTag({ content: gremlins })
  await page.evaluate(() => {
    // @ts-ignore
    const horde = gremlins.createHorde();
    horde.seed(1)
    horde.unleash()
    return new Promise((resolve) => {
      horde.after(resolve)
    })
  })
}
```

**Comment by HALLERPierre** [comment]
Hey folks. The Marmelab team is attempting to clean up the Issues backlog. With that, we're closing issues that have been open for an one or more years.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. If the issue pertains to a bug, please re-test for the bug on the latest version of gremlins.js.

The best way to report problems with gremlins.js 2.0 is to file new issues.
