### ISSUE TITLE
Custom Logger functions only receive 'gremlin'/'mogwai'-string instead of full msg

### ISSUE THREAD

**Issue by FloNeu** [marmelab/gremlins.js#83]
Just created an custom logger-object to redirect gremlinJs logging to use native angular logging-module like this: 

// Custom gremlinJS Logger for using Angular std. logging
var angularLogger = {
    log:   function( msg ) { $log.debug( msg ) }
    , info:  function( msg ) { $log.info( msg ) }
    , warn:  function( msg ) { $log.warn( msg ) }
    , error: function( msg ) { $log.error( msg ) }
 } resulting in only 'gremlin'/'mogwai'-logs being written to console.

Verified that passed msg-parameter only contains this information, but couldn't build unminified version for further debugging. What are you using for generating your minified files?

Thank you, great project! All the best!

**Comment by jhulme** [comment]
I'm also experiencing this issue using debugout.js (https://github.com/inorganik/debugout.js) as a custom logger.

var bugout = new debugout();

var customLogger = {
log: bugout.log,
info: bugout.log,
warn: bugout.log,
error: bugout.log
};

**Comment by jhulme** [comment]
I took a small look at this issue over the weekend and determined that the problem was with debugout.js only accepting a single argument to the .log method.

Each of the gremlins has been implemented to output multiple items e.g

            if (typeof config.logger.log == 'function') {
                config.logger.log('gremlin', 'scroller  ', 'scroll to', scrollX, scrollY);

I'm now looking at re-writing the log function within debugout.js to allow for multiple items.

Cheers.

**Comment by fzaninotto** [comment]
So... Can we consider this is not a gremlins.js issue, and close it?

**Comment by jhulme** [comment]
It might be beneficial to add something to the 'Customizing The Logger' section of the readme.md, perhaps?

It is definitely not a gremlins.js issue.

Cheers.

**Comment by HALLERPierre** [comment]
Hey folks. The Marmelab team is attempting to clean up the Issues backlog. With that, we're closing issues that have been open for an one or more years.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. If the issue pertains to a bug, please re-test for the bug on the latest version of gremlins.js.

The best way to report problems with gremlins.js 2.0 is to file new issues.
