### ISSUE TITLE
Other metric to measure the robustness of webpage except "fps"

### ISSUE THREAD

**Issue by luisxiaomai** [marmelab/gremlins.js#84]
I used gremlins, it's cool. But it always failed based on some e-commerce website, because of "fps". Do we have other metric to measure the robustness of web page?

**Comment by midgettj** [comment]
If possible i think a 'memory' Mogwai would be nice to have as a metric for performance

**Comment by HALLERPierre** [comment]
Hey folks. The Marmelab team is attempting to clean up the Issues backlog. With that, we're closing issues that have been open for an one or more years.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. If the issue pertains to a bug, please re-test for the bug on the latest version of gremlins.js.

The best way to report problems with gremlins.js 2.0 is to file new issues.
