### ISSUE TITLE
Alternative to Bookmarklet in mobile browsers

### ISSUE THREAD

**Issue by madhavpai2000** [marmelab/gremlins.js#85]
Hi,

Is there a way to use this javascript function other than bookmarklet inorder to make it work on mobile browsers on Android

javascript:(function(){function callback(){gremlins.createHorde().allGremlins().gremlin(function() {window.$ = function() {};}).unleash()}  var s=document.createElement("script");s.src="https://rawgithub.com/marmelab/gremlins.js/master/gremlins.min.js";if(s.addEventListener){s.addEventListener("load",callback,false)}else if(s.readyState){s.onreadystatechange=callback}document.body.appendChild(s);})()

Please suggest

Regards,
Madhav Pai

**Comment by madhavpai2000** [comment]
can someone tell me a way out please????

**Comment by fzaninotto** [comment]
Did you try adding the gremlins library as a script tag? That's how it's supposed to work.

**Comment by madhavpai2000** [comment]
My requirement is not to put it under any source. Am supposed to run it say
for eg 100 websites to check the stability of my browser app. Can there be
a way out?

**Comment by fzaninotto** [comment]
Sorry, I don't get your point.

**Comment by madhavpai2000** [comment]
We test our browser application for stability. We take hundred random
websites and run gremlins lib on iy. But since bookmarklet is not supported
we would like to know an alternative to execute gremlins lib on our random
list of website

**Comment by fzaninotto** [comment]
Ah, this is not a library to test browsers, it'a a library to test webapps running inside a browser. Sorry.

**Comment by madhavpai2000** [comment]
Yes am testing the website itself within the browser. But i just want to
know how do i use gremlins to test webapps outside the application and
still be able to test the application
