### ISSUE TITLE
New release wanted

### ISSUE THREAD

**Issue by redaxmedia** [marmelab/gremlins.js#87]
Is there a chance for a new release that includes the <code>species.toucher()</code>. This issue is related to the Grunt task: https://github.com/kupriyanenko/grunt-gremlins/issues/7

**Comment by joscha** [comment]
I am also keen to get a new release. @fzaninotto is there anyway you can do a publish to npm?

**Comment by joscha** [comment]
Any way we can help with this @fzaninotto @jtangelder ?

**Comment by HALLERPierre** [comment]
Hey folks. The Marmelab team is attempting to clean up the Issues backlog. With that, we're closing issues that have been open for an one or more years.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. If the issue pertains to a bug, please re-test for the bug on the latest version of gremlins.js.

The best way to report problems with gremlins.js 2.0 is to file new issues.

**Comment by redaxmedia** [comment]
Wow, this took just 5 years... haha

Anyway, glad this project is still alive... good work
