### ISSUE TITLE
This gremlin requires a randomizer to run. Please call randomizer(randomizerObject) before executing the gremlin

### ISSUE THREAD

**Issue by op1ekun** [marmelab/gremlins.js#93]
From README.md

_"For instance, the clicker gremlin is a function that you can execute it directly:"_

```
var clickerGremlin = gremlins.species.clicker();
clickerGremlin(); // trigger a random mouse even in the screen
```

The code above raises this error:

```
This gremlin requires a randomizer to run. 
Please call randomizer(randomizerObject) before executing the gremlin
```

ENV:
Windows Server 2012 R2
Chrome Version 46.0.2490.86 m
gremlins.min.js from master branch

**Comment by HALLERPierre** [comment]
Hey folks. The Marmelab team is attempting to clean up the Issues backlog. With that, we're closing issues that have been open for an one or more years.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. If the issue pertains to a bug, please re-test for the bug on the latest version of gremlins.js.

The best way to report problems with gremlins.js 2.0 is to file new issues.
