### ISSUE TITLE
TypeError: 'undefined' is not an object (evaluating 'gremlins.spieces.typer')

### ISSUE THREAD

**Issue by op1ekun** [marmelab/gremlins.js#94]
Running:

```
gremlins.createHorde()
    .gremlin(gremlins.spieces.typer().eventTypes(['keypress']))
    .unleash();
```

gives me the above error.

ENV:
Windows Server 2012 R2
Chrome Version 46.0.2490.86 m
gremlins.min.js from master branch

**Comment by kafeltz** [comment]
I think this kind of bug is better solved when visualized. Jsfiddle?

**Comment by op1ekun** [comment]
Hi :)
What do you want me to visualize? I just run the three line of code I pasted above. The error is what I get in Chrome's console. That is all what is necessary to reproduce the bug.

I will try to create JsFiddle though.

**Comment by op1ekun** [comment]
Here's the fiddle: http://jsfiddle.net/op1ekun/bgpphco5/

**Comment by kafeltz** [comment]
I think i got it! Mistype "species". Take a look, you typed "spieces", so it gives undefined objects.

species !== spieces

**Comment by op1ekun** [comment]
:DDDDD

Damn typo ... I was using auto-complete when I was trying it from console, but I typed it manually when I added it to the app.

Good catch! Thanks!
