### ISSUE TITLE
is it dead?

### ISSUE THREAD

**Issue by DarkPark** [marmelab/gremlins.js#95]
https://www.npmjs.com/package/gremlins.js
published 2 years ago
are there really no updates since then?

**Comment by kafeltz** [comment]
I don't know either, but it's kinda stable yet.

**Comment by DarkPark** [comment]
seems to me as well
but then it would be nice to have the corresponding npm package in actual state

**Comment by fzaninotto** [comment]
No it's not dead, it's just that we (marmelab) have a lot of OSS projects to maintain, so we deal with priorities. As @kafeltz says, it's pretty stable already.

**Comment by DarkPark** [comment]
so why don't you release npm module?
