### ISSUE TITLE
initKeyboardEvent error

### ISSUE THREAD

**Issue by forresto** [marmelab/gremlins.js#99]
With

``` js
import Gremlins from 'gremlins.js'
Gremlins.createHorde().unleash()
```

This error in console: 

> Uncaught TypeError: Failed to execute 'initKeyboardEvent' on 'KeyboardEvent': parameter 4 is not of type 'Window'. gremlins.min.js?61fa:22

**Comment by forresto** [comment]
`import Gremlins from 'gremlins.js/src/main'` seems to fix it, so it might be a double-build issue.

**Comment by thepianist2** [comment]
I have the same problem, but y import the library on the index.html 

<script src="/vendor/gremlins.js/gremlins.min.js"></script>
<script>
gremlins.createHorde().unleash();
</script>

**Comment by thepianist2** [comment]
I have been researching , and the version on the repository: https://github.com/marmelab/gremlins.js

It is different from that found in bower and npm .

Specifically this file :

https://github.com/marmelab/gremlins.js/blob/master/src/species/typer.js

It is not the same, in the version that failure bower and npm this line is the one that fails:

line 84
` KeyboardEvent [ initMethod ] ( config.randomizer.pick ( config.eventTypes ) , ` true , true , targetElement , false, false , false, false , key , ` 0); `


To fix it I imported the file repository :

https://github.com/marmelab/gremlins.js/blob/master/gremlins.min.js

and it is working properly.

**Comment by bcherny** [comment]
@thepianist2 Fix worked for me-

Before: `npm i gremlins.js`
After: `npm i marmelab/gremlins.js`

**Comment by cdbusby** [comment]
@bcherny & @thepianist2  this fixed it for me as well. Would be good to have the bower/npm versions updated!

**Comment by roopemerikukka** [comment]
Having the same error even if I install the github version. Using latest Chrome on Mac. I think #97 should fix this?

**Comment by sarukuku** [comment]
Run into this issue too

**Comment by dbartholomae** [comment]
@fzaninotto A release would be great to fix this :)

**Comment by HALLERPierre** [comment]
Hey folks. The Marmelab team is attempting to clean up the Issues backlog. With that, we're closing issues that have been open for an one or more years.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. If the issue pertains to a bug, please re-test for the bug on the latest version of gremlins.js.

The best way to report problems with gremlins.js 2.0 is to file new issues.
